[package]
name = "clap-vergen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"

[build-dependencies]
anyhow = "1.0.59"
vergen = "7.3.2"
