[package]
name = "clap-vergen-example"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }

[dependencies.clap-vergen]
path = "../clap-vergen"

[build-dependencies]
vergen = "7.3.2"
